FROM ocaml/opam:debian-11-ocaml-4.14@sha256:70bd0da74f68550d667cc1a8ae80661e694cd9ac614273b23c45f3fb8a9f3ac9 AS build
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN sudo apt-get update && sudo apt-get install libev-dev capnproto m4 pkg-config libgmp-dev nodejs yarn -y --no-install-recommends
RUN cd ~/opam-repository && git pull origin master && git reset --hard ec387d9c255ba187a10c49b7ac0ce26b727d9a0b && opam update
COPY --chown=opam \
	ocurrent/current_rpc.opam \
	/src/ocurrent/
WORKDIR /src
RUN opam pin -yn add ./ocurrent
COPY --chown=opam ocaml-multicore-ci-api.opam ocaml-multicore-ci-web.opam /src/
RUN opam install -y --deps-only .
ADD --chown=opam . .
RUN opam config exec -- dune build ./_build/install/default/bin/ocaml-multicore-ci-web
RUN cd /src/web-app && yarn install && yarn build

FROM debian:11
RUN apt-get update && apt-get install libev4 ca-certificates dumb-init -y --no-install-recommends
WORKDIR /
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/local/bin/ocaml-multicore-ci-web", "--admin-service-uri", "https://multicore.ci.ocamllabs.io:8100/", "--docroot", "/srv"]
EXPOSE 8090/tcp
COPY --from=build /src/_build/install/default/bin/ocaml-multicore-ci-web /usr/local/bin/
COPY --from=build /src/web-app/build/ /srv/
